class FastDeque:
    """
    O(1) for `push_back`, `push_front`, `pop_back`, `pop_front`, and random access with index

    No C++ equivalent for "fast" deque in Python is just sad (we only have O(N) random access with `collections.deque`)
    """
    def __init__(self, capacity: int):
        self.capacity = capacity
        self.data = [0] * self.capacity
        self.size = 0
        self.head = 0  # Pointer to front
        self.tail = self.capacity - 1  # Pointer to back

    def push_back(self, item):
        if self.size == self.capacity:
            raise Exception("capacity exceeded, can't push new item")
        
        self.size += 1
        self.tail += 1
        if self.tail == self.capacity:
            self.tail = 0
        self.data[self.tail] = item

    def pop_back(self):
        if self.size == 0:
            raise Exception("empty data, can't pop")
        
        item = self.data[self.tail]

        self.size -= 1
        self.tail -= 1
        if self.tail == -1:
            self.tail = self.capacity - 1
        
        return item
        
    def push_front(self, item):
        if self.size == self.capacity:
            raise Exception("capacity exceeded, can't push new item")
        
        self.size += 1
        self.head -= 1
        if self.head < 0:
            self.head = self.capacity - 1
        self.data[self.head] = item

    def pop_front(self):
        if self.size == 0:
            raise Exception("empty data, can't pop")
        
        item = self.data[self.head]
        
        self.size -= 1
        self.head += 1
        if self.head == self.capacity:
            self.head = 0

        return item

    def __getitem__(self, i):
        if i < 0:
            i += self.size # Handle negative indices like q[-1]
            
        if i >= self.size or i < 0:
            raise IndexError("index out of range")

        i = (self.head + i) % self.capacity
        return self.data[i]

    def __repr__(self):
        return str([self[i] for i in range(self.size)])

if __name__ == "__main__":
    # Tests are generated by gemini :)
    print("Running Tests...")

    # 1. Basic Push/Pop Back
    q = FastDeque(capacity=5)
    q.push_back(10)
    q.push_back(20)
    q.push_back(30)
    assert str(q) == "[10, 20, 30]"
    assert q.pop_back() == 30
    assert q.pop_back() == 20
    assert str(q) == "[10]"
    print("✓ Basic Push/Pop Back Passed")

    # 2. Basic Push/Pop Front
    q = FastDeque(capacity=5)
    q.push_front(10)
    q.push_front(20)
    assert str(q) == "[20, 10]"
    assert q.pop_front() == 20
    assert str(q) == "[10]"
    print("✓ Basic Push/Pop Front Passed")

    # 3. Interleaved Ops (Queue behavior)
    q = FastDeque(capacity=5)
    q.push_back(1)
    q.push_back(2)
    q.push_front(0) # [0, 1, 2]
    assert q[0] == 0
    assert q[2] == 2
    assert q.pop_back() == 2 # [0, 1]
    assert q.pop_front() == 0 # [1]
    assert str(q) == "[1]"
    print("✓ Interleaved Ops Passed")

    # 4. Circular Wrap-Around Logic
    # This is the most critical test for this data structure
    q = FastDeque(capacity=3)
    q.push_back('a')
    q.push_back('b')
    q.push_back('c') # Full: ['a', 'b', 'c']
    
    # Pop from front to move head forward
    assert q.pop_front() == 'a' # Internal array might look like [None, 'b', 'c'] (head at 1)
    
    # Push back to trigger tail wrap-around
    q.push_back('d') 
    # Logical: ['b', 'c', 'd']. Physical array likely ['d', 'b', 'c']
    
    assert str(q) == "['b', 'c', 'd']"
    assert q[0] == 'b'
    assert q[2] == 'd'
    print("✓ Circular Wrap-Around Passed")

    # 5. Random Access & Negative Indexing
    q = FastDeque(capacity=5)
    for i in range(5):
        q.push_back(i * 10) # [0, 10, 20, 30, 40]
    
    assert q[0] == 0
    assert q[4] == 40
    assert q[-1] == 40
    assert q[-2] == 30
    
    try:
        val = q[5] # Out of bounds
        print("X Index Error Check Failed (Positive)")
    except IndexError:
        pass # Expected
        
    try:
        val = q[-6] # Out of bounds negative
        print("X Index Error Check Failed (Negative)")
    except IndexError:
        pass # Expected
    print("✓ Random Access Passed")

    # 6. Capacity Limits
    q = FastDeque(capacity=2)
    q.push_back(1)
    q.push_back(2)
    try:
        q.push_back(3) # Should fail
        print("X Capacity Overflow Check Failed")
    except Exception as e:
        assert "capacity exceeded" in str(e)

    q.pop_front()
    q.pop_front() # Empty now
    try:
        q.pop_front() # Should fail
        print("X Empty Pop Check Failed")
    except Exception as e:
        assert "empty data" in str(e)
    print("✓ Capacity/Empty Checks Passed")

    print("\nALL TESTS PASSED SUCCESSFULLY!")